[2024-06-30T09:03:30.650+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-30T09:03:30.672+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwindDWH.data_delivery manual__2024-06-30T08:53:53.031867+00:00 [queued]>
[2024-06-30T09:03:30.680+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwindDWH.data_delivery manual__2024-06-30T08:53:53.031867+00:00 [queued]>
[2024-06-30T09:03:30.680+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-06-30T09:03:30.692+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-30 08:53:53.031867+00:00
[2024-06-30T09:03:30.700+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=165) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-30T09:03:30.701+0000] {standard_task_runner.py:63} INFO - Started process 167 to run task
[2024-06-30T09:03:30.702+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'northwindDWH', 'data_delivery', 'manual__2024-06-30T08:53:53.031867+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/northwindDWH.py', '--cfg-path', '/tmp/tmp_plb3ylf']
[2024-06-30T09:03:30.703+0000] {standard_task_runner.py:91} INFO - Job 98: Subtask data_delivery
[2024-06-30T09:03:30.714+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-30T09:03:30.742+0000] {task_command.py:426} INFO - Running <TaskInstance: northwindDWH.data_delivery manual__2024-06-30T08:53:53.031867+00:00 [running]> on host 3abb3aef8f21
[2024-06-30T09:03:30.824+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='northwindDWH' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-30T08:53:53.031867+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-30T08:53:53.031867+00:00'
[2024-06-30T09:03:30.825+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-30T09:03:30.838+0000] {northwindDWH.py:49} INFO - Data delivery started
[2024-06-30T09:03:30.838+0000] {Load_data.py:85} INFO - loading dimEmployee to db ...
[2024-06-30T09:03:30.838+0000] {Transform_data.py:51} INFO - start Extracting dim employee
[2024-06-30T09:03:30.841+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T09:03:30.844+0000] {Transform_data.py:60} INFO - Extract dim employees done
[2024-06-30T09:03:30.845+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T09:03:30.849+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T09:03:30.851+0000] {Load_data.py:103} INFO - SCD type 2 on dimemployee started
[2024-06-30T09:03:30.858+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T09:03:30.858+0000] {Load_data.py:159} INFO - Loading dimproduct to db...
[2024-06-30T09:03:30.858+0000] {Transform_data.py:27} INFO - Start Extracting dim product
[2024-06-30T09:03:30.861+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T09:03:30.863+0000] {Transform_data.py:41} INFO - Extract dim products done
[2024-06-30T09:03:30.864+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T09:03:30.867+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T09:03:30.870+0000] {Load_data.py:172} INFO - SCD type 1 on dimproduct started
[2024-06-30T09:03:30.884+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: integer out of range

[2024-06-30T09:03:30.885+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:03:30.886+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:03:30.887+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:03:30.888+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:03:30.889+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:03:30.890+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:03:30.891+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:03:30.892+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:03:30.892+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:03:30.893+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:03:30.894+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:03:30.895+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:03:30.896+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:03:30.898+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:03:30.898+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T09:03:30.898+0000] {Load_data.py:223} INFO - Loading dim_products completed successfully
[2024-06-30T09:03:30.898+0000] {Load_data.py:12} INFO - loading dimCustomers to db ...
[2024-06-30T09:03:30.899+0000] {Transform_data.py:7} INFO - start Extracting dim customers
[2024-06-30T09:03:30.901+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T09:03:30.903+0000] {Transform_data.py:16} INFO - Extract dim customer done
[2024-06-30T09:03:30.904+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T09:03:30.907+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T09:03:30.909+0000] {Load_data.py:30} INFO - SCD type 2 on dimcustomer started
[2024-06-30T09:03:30.922+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T09:03:30.923+0000] {Load_data.py:231} INFO - Loading factsales to db ...
[2024-06-30T09:03:30.923+0000] {Transform_data.py:70} INFO - start Extracting fact sales
[2024-06-30T09:03:30.926+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T09:03:30.929+0000] {Transform_data.py:81} INFO - Extract fact sales done
[2024-06-30T09:03:30.929+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T09:03:30.932+0000] {Tables_creations.py:27} INFO - Loading data into table fact_sales...
[2024-06-30T09:03:30.935+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T09:03:30.950+0000] {Tables_creations.py:41} INFO - Data loaded successfully into table fact_sales With 58 Row
[2024-06-30T09:03:30.950+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T09:03:30.950+0000] {Load_data.py:239} INFO - Fact_Sales loaded successfully
[2024-06-30T09:03:30.950+0000] {northwindDWH.py:54} INFO - Data delivery done
[2024-06-30T09:03:30.951+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-30T09:03:30.951+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-30T09:03:30.959+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=northwindDWH, task_id=data_delivery, run_id=manual__2024-06-30T08:53:53.031867+00:00, execution_date=20240630T085353, start_date=20240630T090330, end_date=20240630T090330
[2024-06-30T09:03:30.995+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-30T09:03:31.010+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-30T09:03:31.012+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
